import Header from "./header/Header";
import Footer from "./footer/Footer";
import WhenToContactWho from "./WhenToContactWhom/WhenToContactWho";
import PositiveMessage from "./positiveMessage/PositiveMessage";
import ComingSoon from "./commingSoon/CommingSoon";
import FishDetails from "./FishDetails/FishDetails";
import OurGallary from "./ourGallary/OurGallary";
import FishAnimation from "./fishAnimation/FishAnimation";
import HeaderContent from "./headerContent/HeaderContent";
import BackToTop from "./backToTop/BackToTop";
export {Header,ComingSoon, HeaderContent,Footer, WhenToContactWho, PositiveMessage,FishDetails, OurGallary, FishAnimation};